steps:

# Step 0
#docker build the image from httpd public dockerhub Apache image

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/haks-c1/my-docker-repo/httpd-image', '.' ]
options:
  logging: CLOUD_LOGGING_ONLY
  build:
    service_account: 669157487352-compute@developer.gserviceaccount.com 	
    logs_bucket: haks-c1-bucket
    
# Step 1
#push the previously built image to ythe docker repo created in Step 0
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/haks-c1/my-docker-repo/httpd-image']


# Step 2
# Publish the release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - > 
      gcloud deploy releases create release-$BUILD_ID
      --delivery-pipeline=my-demo-app
      --region=us-central1
      --images=my-app-image=us-central1-docker.pkg.dev/haks-c1/my-docker-repo/httpd-image
      --source=./
      --logsBucket=haks-c1-bucket
